name: webatlas
channels:
  - conda-forge
dependencies:
  - colorama=0.4.6
  - dask=2023.9.0
  - fire=0.5.0
  - fsspec=2023.9.2
  - h5py=3.10.0
  - imagecodecs=2023.8.12
  - markupsafe=2.1.3
  - nodejs=20.5.1
  - numba=0.58.1
  - numcodecs=0.12.1
  - numpy=1.24.4
  - openjdk=11
  - openjpeg=2.5.0
  - pandas=2.1.0
  - pip=23.2.1
  - python=3.9
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pyvips=2.2.1
  - regex=2023.10.3
  - scanpy=1.9.5
  - scikit-image=0.21.0
  - scikit-learn=1.3.1
  - scipy=1.11.2
  - setuptools=68.1.2
  - shapely=2.0.1
  - snappy=1.1.10
  - tifffile=2023.8.30
  - umap-learn=0.5.3
  - wheel=0.41.2
  - zarr=2.16.1
  - bioconda::nextflow=23.04.1
  - ome::bioformats2raw=0.7.0
  - ome::bioformats2raw-libs=0.7.0
  - ome::raw2ometiff=0.5.0=0
  - ome::raw2ometiff-libs=0.5.0=0
  - pip:
      - apeer-ometiff-library==1.9.0
      - ome-zarr==0.8.2
